version: "3.5"

services:
    frontend:
        build: .
        ports:
          - "${FRONTEND_PORT:-8080}:8080"
        volumes:
            - "./:/frontend/"
            - "/frontend/node_modules"
